# Generated by Django 3.1.5 on 2021-04-04 22:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listRtoOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rto_code', models.IntegerField(default=43)),
                ('add', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VechileFine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vechile_no', models.CharField(max_length=12)),
                ('fine', models.CharField(choices=[('Driving without license', 'Driving without license'), ('Unauthorized use of vehicles', 'Unauthorized use of vehicles'), ('Driving without qualification', 'Driving without qualification'), ('Rash Driving', 'Rash Driving'), ('Speeding', 'Speeding'), ('Drunken Driving', 'Drunken Driving')], max_length=100)),
                ('charge', models.IntegerField()),
                ('offence_on', models.DateField(default=datetime.datetime(2021, 4, 5, 3, 35, 42, 676217))),
                ('paid_upto', models.DateField(default=datetime.datetime(2021, 6, 5, 3, 35, 42, 676217))),
                ('state', models.CharField(choices=[('select', 'select'), (' Maharashtra', ' Maharashtra'), ('Andhra Pradesh', 'Andhra Pradesh'), (' Assam', ' Assam'), (' Arunachal Pradesh', ' Arunachal Pradesh'), (' Bihar', ' Bihar'), (' Goa', ' Goa'), (' Gujarat', ' Gujarat'), (' Jammu and Kashmir', ' Jammu and Kashmir'), (' Jharkhand', ' Jharkhand'), (' West Bengal', ' West Bengal'), (' Karnataka', ' Karnataka'), ('Kerala', ' Kerala'), (' Madhya Pradesh', ' Madhya Pradesh'), (' Manipur', ' Manipur'), (' Meghalaya', ' Meghalaya'), (' Mizoram', ' Mizoram'), (' Nagaland', ' Nagaland'), (' Orissa', ' Orissa')], max_length=20)),
            ],
            managers=[
                ('man_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RCRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vechile_no', models.CharField(max_length=10)),
                ('owner', models.CharField(max_length=25)),
                ('fuel_type', models.CharField(choices=[('Select Fuel Type', 'Select Fuel Type'), ('Petrol', 'Petrol'), ('Petrol+CNG', 'Petrol + CNG'), ('Diesel', 'Diesel'), ('CNG', 'CNG')], max_length=100)),
                ('reg_date', models.DateField(default=datetime.datetime(2021, 4, 5, 3, 35, 42, 676217))),
                ('insurance', models.DateField()),
                ('permit_expiry', models.DateField()),
                ('permit_no', models.CharField(max_length=20)),
                ('fitness', models.CharField(max_length=10)),
                ('rto_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_1.listrtooffice')),
            ],
            managers=[
                ('man_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LicenseRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dl', models.CharField(max_length=20, unique=True)),
                ('owner', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('doi', models.DateField(default=datetime.datetime(2021, 4, 5, 3, 35, 42, 676217))),
                ('expiry', models.DateField()),
                ('vechile_class', models.CharField(choices=[('Select COV', 'Select COV'), ('MCWOG', 'MCWOG'), ('CVG', 'CVG'), ('MCWOG/FVG', 'MCWOG/FVG'), ('LMV-NT', 'LMV-NT'), ('MGV', 'MGV'), ('HMV', 'HMV'), ('HPMV/HTV', 'HPMV/HTV')], max_length=20)),
                ('cov_issue', models.DateField()),
                ('last_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_1.listrtooffice')),
            ],
            managers=[
                ('man_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
