# Generated by Django 3.1.5 on 2021-04-15 21:31

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('django_twilio', '0001_initial'),
        ('App_1', '0004_auto_20210416_0259'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Officers',
            new_name='Officer',
        ),
        migrations.AlterField(
            model_name='licenseregistration',
            name='doi',
            field=models.DateField(default=datetime.datetime(2021, 4, 16, 3, 1, 18, 872290)),
        ),
        migrations.AlterField(
            model_name='rcregister',
            name='reg_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 16, 3, 1, 18, 872290)),
        ),
        migrations.AlterField(
            model_name='vechilefine',
            name='offence_on',
            field=models.DateField(default=datetime.datetime(2021, 4, 16, 3, 1, 18, 872290)),
        ),
        migrations.AlterField(
            model_name='vechilefine',
            name='paid_upto',
            field=models.DateField(default=datetime.datetime(2021, 6, 16, 3, 1, 18, 872290)),
        ),
        migrations.AlterModelTable(
            name='officer',
            table='Officer',
        ),
    ]
