# Generated by Django 3.1.5 on 2021-04-15 21:54

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0005_auto_20210416_0301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderator',
            options={},
        ),
        migrations.AlterModelManagers(
            name='moderator',
            managers=[
                ('man_objects', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='officer',
            managers=[
                ('man_objects', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='licenseregistration',
            name='doi',
            field=models.DateField(default=datetime.datetime(2021, 4, 16, 3, 24, 51, 106962)),
        ),
        migrations.AlterField(
            model_name='rcregister',
            name='reg_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 16, 3, 24, 51, 106962)),
        ),
        migrations.AlterField(
            model_name='vechilefine',
            name='offence_on',
            field=models.DateField(default=datetime.datetime(2021, 4, 16, 3, 24, 51, 106962)),
        ),
        migrations.AlterField(
            model_name='vechilefine',
            name='paid_upto',
            field=models.DateField(default=datetime.datetime(2021, 6, 16, 3, 24, 51, 106962)),
        ),
        migrations.AlterModelTable(
            name='moderator',
            table='Moderator',
        ),
    ]
