# Generated by Django 3.1.5 on 2021-04-15 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0007_auto_20210416_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseregistration',
            name='doi',
            field=models.DateField(default=datetime.datetime(2021, 4, 16, 3, 32, 11, 728672)),
        ),
        migrations.AlterField(
            model_name='rcregister',
            name='reg_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 16, 3, 32, 11, 728672)),
        ),
        migrations.AlterField(
            model_name='vechilefine',
            name='offence_on',
            field=models.DateField(default=datetime.datetime(2021, 4, 16, 3, 32, 11, 728672)),
        ),
        migrations.AlterField(
            model_name='vechilefine',
            name='paid_upto',
            field=models.DateField(default=datetime.datetime(2021, 6, 16, 3, 32, 11, 728672)),
        ),
    ]
